"""Hand-written role knowledge used to build the per-role workbooks and by the picker.

ROLES: lolalytics lane name, workbook path, seed champions used to discover the lane's champion pool.
ARCHETYPES[role]: archetype -> (words that describe it in opponents' Good into / Struggles into text,
                                default 'good into' text, default 'struggles into' text)
CHAMPS[role][champion] = (archetype, damage, comps, pick when, blind-safe)
  comps uses the picker's style words: wombo/teamfight, poke/siege, pick, dive, split/flank, scaling/late/front-to-back
DAMAGE: fallback damage type for champions missing from CHAMPS.
Entries are opinions (Claude, Oct 2026); correct them in the generated xlsx, not here, once a workbook exists.
"""

ROLES = {
    "top":     {"lane": "top",     "xlsx": "roles/top.xlsx",     "seeds": ["renekton", "garen", "ornn", "jax"]},
    "jungle":  {"lane": "jungle",  "xlsx": "roles/jungle.xlsx",  "seeds": ["leesin", "viego", "amumu", "graves"]},
    "mid":     {"lane": "middle",  "xlsx": "midlane_overview.xlsx", "seeds": ["ahri", "zed", "orianna"]},
    "bot":     {"lane": "bottom",  "xlsx": "roles/bot.xlsx",     "seeds": ["jinx", "caitlyn", "ezreal", "jhin"]},
    "support": {"lane": "support", "xlsx": "roles/support.xlsx", "seeds": ["thresh", "lulu", "nautilus", "lux"]},
}
ROLE_ALIASES = {"jg": "jungle", "jng": "jungle", "jungler": "jungle", "middle": "mid", "adc": "bot", "bottom": "bot",
                "sup": "support", "supp": "support", "toplane": "top"}

ARCHETYPES = {
    "top": {
        "Juggernaut":   (["juggernaut", "melee", "immobile", "short range"], "melee bruisers and divers that must walk up to him", "ranged tops, kiting, and poke"),
        "Tank":         (["tank", "tanks", "frontline"], "AD melee and all-in divers", "percent-health damage, split pushers, and ranged bullies"),
        "Duelist":      (["duelist", "split", "melee"], "tanks and juggernauts in a 1v1, side lane", "lane bullies early, ranged tops, hard crowd control"),
        "Diver":        (["diver", "divers", "dive", "melee"], "squishy and ranged tops once level 6", "tanks that out-sustain, juggernauts in extended fights"),
        "Ranged bully": (["ranged", "poke", "kiting", "range"], "melee, immobile juggernauts and tanks", "gap closers, divers, and junglers camping"),
        "AP bruiser":   (["mages", "ap", "magic"], "armor stackers and tanks", "ranged bullies and mobile duelists"),
        "Scaling":      (["scaling", "late"], "slow lanes and teams without early pressure", "lane bullies and early dives"),
    },
    "jungle": {
        "Tank engage":   (["tank", "engage", "frontline"], "squishy carries and immobile teams", "percent-health damage and kiting comps"),
        "Assassin":      (["assassin", "assassins", "squishy"], "squishy, immobile carries and scaling comps", "tanks, peel supports, and early invaders"),
        "Skirmisher":    (["skirmisher", "duelist", "melee"], "farming junglers and 1v1 contests", "hard crowd control and poke comps"),
        "Farming carry": (["farming", "scaling", "late"], "passive junglers and scaling games", "early invaders and dive-heavy comps"),
        "AP carry":      (["mages", "ap", "magic"], "AD-heavy enemy teams and armor stackers", "assassins and early aggression"),
        "Early ganker":  (["early", "ganker", "gank"], "scaling junglers and immobile laners", "scaling comps if the early game fails"),
    },
    "bot": {
        "Hypercarry":        (["hypercarry", "scaling", "late"], "passive bot lanes and front-to-back teams", "lane bullies, divers, and assassins"),
        "Lane bully":        (["bully", "early", "lane"], "scaling carries and weak early lanes", "all-in engage supports and scaling into late"),
        "Utility / poke":    (["poke", "utility", "range"], "melee or short-range bot lanes and engage comps", "hypercarries late and dive supports"),
        "Mage bot":          (["mages", "ap", "magic"], "AD-heavy allied teams needing AP, short-range carries", "mobile carries and assassins"),
        "Mobile skirmisher": (["mobile", "skirmisher", "dash"], "immobile carries and poke comps", "point-and-click crowd control and tanks"),
    },
    "support": {
        "Enchanter": (["enchanter", "shield", "heal", "sustain"], "poke lanes and hypercarry partners", "hook and engage supports, assassins"),
        "Engage":    (["engage", "tank", "frontline"], "squishy, immobile lanes and enchanters", "disengage, poke, and kiting comps"),
        "Hook":      (["hook", "pick"], "immobile carries and squishy supports", "tanks that eat hooks and sustain lanes"),
        "Poke mage": (["poke", "mages", "ap", "range"], "melee supports and short-range lanes", "hard engage and assassins"),
        "Peel tank":    (["peel tank", "peel", "warden"], "dive and assassin comps", "poke lanes and scaling enchanters"),
    },
}

DAMAGE = {  # fallback when a champion is not in CHAMPS for the role
    "AP": "Ahri Akali Amumu Anivia Annie Aurelion Sol Aurora Azir Brand Cassiopeia Cho'Gath Diana Ekko Elise Evelynn Fiddlesticks Fizz Galio Gragas Gwen Heimerdinger Hwei Karma Karthus Kassadin Katarina Kayle Kennen LeBlanc Lillia Lissandra Lulu Lux Malzahar Maokai Mel Milio Mordekaiser Morgana Nami Neeko Nidalee Nunu & Willump Orianna Rumble Ryze Seraphine Singed Sona Soraka Swain Sylas Syndra Taliyah Teemo Twisted Fate Veigar Vel'Koz Vex Viktor Vladimir Xerath Yuumi Zilean Zoe Zyra Ziggs Elise Janna Zac Shyvana Volibear Rakan Taric".split(),
}
DAMAGE_OVERRIDE = {"Zac": "AP", "Shyvana": "Mixed", "Volibear": "Mixed", "Kayle": "Mixed", "Gnar": "Mixed", "Jax": "Mixed",
                   "Corki": "Mixed", "Kai'Sa": "Mixed", "Varus": "Mixed", "Kog'Maw": "Mixed", "Rakan": "AP", "Taric": "AP",
                   "Bard": "AP", "Alistar": "AP", "Leona": "AP", "Nautilus": "AP", "Blitzcrank": "AP", "Thresh": "AP",
                   "Braum": "AP", "Rell": "AP", "Tahm Kench": "AP", "Sejuani": "AP", "Poppy": "AD", "Ornn": "AP",
                   "Malphite": "AP", "Sion": "AD", "K'Sante": "AD", "Skarner": "AP", "Rammus": "AP", "Udyr": "Mixed",
                   "Aatrox": "AD", "Mundo": "AD", "Dr. Mundo": "AD"}


def damage_of(champ: str) -> str:
    if champ in DAMAGE_OVERRIDE:
        return DAMAGE_OVERRIDE[champ]
    return "AP" if champ in DAMAGE["AP"] else "AD"


CHAMPS = {
 "top": {
  "Aatrox":      ("Diver", "AD", "teamfight, dive, front-to-back", "You need a frontline with damage and sustain", "Mostly"),
  "Ambessa":     ("Diver", "AD", "dive, pick, flank", "You want a mobile bruiser to dive the backline", "Mostly"),
  "Akali":       ("Diver", "AP", "dive, pick, split", "You need AP and a backline threat", "No"),
  "Camille":     ("Duelist", "AD", "pick, dive, split", "You want a side laner who can lock down a carry", "Mostly"),
  "Cho'Gath":    ("Tank", "AP", "teamfight, front-to-back, scaling", "You need a tank with true damage to kill a tank", "Yes"),
  "Darius":      ("Juggernaut", "AD", "teamfight, dive", "The enemy is melee heavy and you want lane pressure", "Mostly"),
  "Dr. Mundo":   ("Tank", "AD", "front-to-back, scaling", "You need a frontline against AP-heavy teams", "Yes"),
  "Fiora":       ("Duelist", "AD", "split, scaling", "The enemy has tanks and you can play side lane", "Mostly"),
  "Gangplank":   ("Scaling", "AD", "poke, siege, scaling, teamfight", "Your team scales and needs a global ult", "Mostly"),
  "Garen":       ("Juggernaut", "AD", "teamfight, front-to-back", "You need a simple, safe frontline", "Yes"),
  "Gnar":        ("Ranged bully", "Mixed", "wombo, teamfight, poke", "You want a ranged top with a wombo ult", "Mostly"),
  "Gragas":      ("AP bruiser", "AP", "wombo, teamfight, pick", "You need AP, engage, and disengage from top", "Yes"),
  "Gwen":        ("Duelist", "AP", "split, scaling, teamfight", "You need AP and anti-tank damage", "Mostly"),
  "Heimerdinger":("Ranged bully", "AP", "siege, poke", "You want to bully a melee top and siege", "No"),
  "Illaoi":      ("Juggernaut", "AD", "teamfight, front-to-back", "The enemy is melee and dives in on you", "Mostly"),
  "Irelia":      ("Duelist", "AD", "dive, split, teamfight", "You want a snowballing duelist against immobile tops", "No"),
  "Jax":         ("Duelist", "Mixed", "split, scaling, dive", "You want a late-game split pusher", "Yes"),
  "Jayce":       ("Ranged bully", "AD", "poke, siege", "You want to bully a melee top and poke in sieges", "Mostly"),
  "K'Sante":     ("Tank", "AD", "teamfight, pick, front-to-back", "You need a tank who can also kill a carry", "Yes"),
  "Kayle":       ("Scaling", "Mixed", "scaling, late, front-to-back", "The game will go long and your team can protect you", "No"),
  "Kennen":      ("Ranged bully", "AP", "wombo, teamfight", "You need AP and a teamfight ult, and the enemy top is melee", "Mostly"),
  "Kled":        ("Diver", "AD", "dive, teamfight, pick", "You want engage from top and a lane bully", "Mostly"),
  "Malphite":    ("Tank", "AP", "wombo, teamfight", "The enemy is AD heavy and you need a wombo engage", "Yes"),
  "Maokai":      ("Tank", "AP", "wombo, teamfight, front-to-back", "You need a safe tank with engage", "Yes"),
  "Mordekaiser": ("Juggernaut", "AP", "teamfight, pick, split", "You need AP and want to isolate a carry", "Yes"),
  "Nasus":       ("Scaling", "AD", "split, scaling, late", "The enemy top cannot punish stacking", "Mostly"),
  "Olaf":        ("Juggernaut", "AD", "dive, teamfight", "The enemy relies on crowd control to kite", "Mostly"),
  "Ornn":        ("Tank", "AP", "wombo, teamfight, scaling", "You need a safe tank with a teamfight ult and upgrades", "Yes"),
  "Pantheon":    ("Diver", "AD", "dive, pick, teamfight", "You want early lane dominance and a global", "Mostly"),
  "Poppy":       ("Tank", "AD", "teamfight, pick", "The enemy has dashes and you need a tank", "Yes"),
  "Quinn":       ("Ranged bully", "AD", "pick, split, poke", "You want to bully a melee top and roam", "No"),
  "Renekton":    ("Diver", "AD", "dive, teamfight", "You want early pressure and a frontline bruiser", "Mostly"),
  "Riven":       ("Duelist", "AD", "dive, split, pick", "You want to snowball a lane against a slow top", "No"),
  "Rumble":      ("AP bruiser", "AP", "wombo, teamfight", "You need AP and a zoning teamfight ult", "Mostly"),
  "Sett":        ("Juggernaut", "AD", "teamfight, dive, front-to-back", "You want a frontline bruiser with a comp-friendly ult", "Yes"),
  "Shen":        ("Tank", "Mixed", "teamfight, split, front-to-back", "You want a global to protect your carry", "Yes"),
  "Singed":      ("AP bruiser", "AP", "split, teamfight", "The enemy top cannot stop proxy farming", "Mostly"),
  "Sion":        ("Tank", "AD", "teamfight, front-to-back, split", "You need a tank who can also push side lanes", "Yes"),
  "Tahm Kench":  ("Tank", "AP", "front-to-back, teamfight", "The enemy is melee and you need peel", "Yes"),
  "Teemo":       ("Ranged bully", "AP", "poke, split", "You want to bully a melee top with no gap closer", "No"),
  "Tryndamere":  ("Duelist", "AD", "split, scaling", "You want to split push and the enemy lacks crowd control", "Mostly"),
  "Trundle":     ("Juggernaut", "AD", "split, teamfight, front-to-back", "The enemy has tanks you need to shred", "Mostly"),
  "Urgot":       ("Juggernaut", "AD", "teamfight, front-to-back", "The enemy is melee and you want a safe lane", "Yes"),
  "Vayne":       ("Ranged bully", "AD", "scaling, split", "The enemy has tanks and a melee top", "No"),
  "Vladimir":    ("Scaling", "AP", "wombo, teamfight, scaling", "You need AP and the game will go long", "Mostly"),
  "Volibear":    ("Juggernaut", "Mixed", "dive, teamfight", "You want a tanky diver who turns around ganks", "Yes"),
  "Warwick":     ("Duelist", "Mixed", "dive, pick", "You want sustain in lane and a point-and-click pick", "Yes"),
  "Wukong":      ("Diver", "AD", "wombo, teamfight, dive", "You need a wombo engage from top", "Mostly"),
  "Yasuo":       ("Duelist", "AD", "wombo, teamfight, dive", "Your team has knockups and you need a carry", "No"),
  "Yone":        ("Duelist", "Mixed", "dive, teamfight, scaling", "You want a carry top who scales", "Mostly"),
  "Yorick":      ("Juggernaut", "AD", "split", "You want to split push against a slow top", "Mostly"),
  "Zac":         ("Tank", "AP", "wombo, teamfight", "You need engage from far away", "Yes"),
 },
 "jungle": {
  "Amumu":       ("Tank engage", "AP", "wombo, teamfight", "You need a wombo engage and the enemy clumps", "Yes"),
  "Bel'Veth":    ("Farming carry", "AD", "scaling, split, dive", "Your team can play safe while you scale", "Mostly"),
  "Briar":       ("Skirmisher", "AD", "dive, pick", "You want aggressive skirmishes and a long-range engage", "Mostly"),
  "Diana":       ("AP carry", "AP", "wombo, teamfight, dive", "You need AP and a backline dive", "Mostly"),
  "Ekko":        ("AP carry", "AP", "dive, pick, scaling", "You need a safe AP carry with escape", "Mostly"),
  "Elise":       ("Early ganker", "AP", "dive, pick", "You want early dives and the enemy jungler scales", "Mostly"),
  "Evelynn":     ("Assassin", "AP", "pick, flank", "The enemy has squishy, immobile carries and little vision", "No"),
  "Fiddlesticks":("AP carry", "AP", "wombo, teamfight, pick", "The enemy clumps and you can flank", "Mostly"),
  "Graves":      ("Farming carry", "AD", "scaling, pick, teamfight", "You want a safe, fast-clearing carry", "Yes"),
  "Hecarim":     ("Skirmisher", "AD", "dive, teamfight, wombo", "You want early tempo and a dive engage", "Mostly"),
  "Ivern":       ("Tank engage", "AP", "front-to-back, teamfight", "Your carries need peel and shields", "Mostly"),
  "Jarvan IV":   ("Early ganker", "AD", "wombo, teamfight, dive", "You want early ganks and a teamfight engage", "Yes"),
  "Jax":         ("Skirmisher", "Mixed", "split, scaling, dive", "You want to scale into a late-game duelist", "Yes"),
  "Karthus":     ("AP carry", "AP", "scaling, teamfight, siege", "You need AP and the game will go long", "Mostly"),
  "Kayn":        ("Assassin", "AD", "dive, pick, flank", "You can choose form based on the enemy comp", "Yes"),
  "Kha'Zix":     ("Assassin", "AD", "pick, flank", "The enemy has isolated, squishy carries", "Mostly"),
  "Kindred":     ("Farming carry", "AD", "scaling, teamfight, front-to-back", "You want a ranged carry jungler with a save ult", "Mostly"),
  "Lee Sin":     ("Early ganker", "AD", "dive, pick, teamfight", "You want early pressure and a playmaking kick", "Yes"),
  "Lillia":      ("AP carry", "AP", "wombo, teamfight, scaling", "You need AP and the enemy is melee and clumps", "Mostly"),
  "Maokai":      ("Tank engage", "AP", "wombo, teamfight, front-to-back", "You need a tank with engage", "Yes"),
  "Master Yi":   ("Farming carry", "AD", "scaling, dive", "The enemy lacks crowd control", "No"),
  "Naafiri":     ("Assassin", "AD", "pick, dive", "The enemy has squishy carries and you want fast ganks", "Mostly"),
  "Nidalee":     ("Early ganker", "AP", "poke, pick, dive", "You want early tempo and poke", "No"),
  "Nocturne":    ("Assassin", "AD", "dive, pick", "The enemy relies on vision and has squishy carries", "Mostly"),
  "Nunu & Willump":("Tank engage", "AP", "teamfight, front-to-back", "You want objective control and a safe tank", "Yes"),
  "Pantheon":    ("Early ganker", "AD", "dive, pick, teamfight", "You want early game pressure and a global", "Mostly"),
  "Poppy":       ("Tank engage", "AD", "teamfight, pick", "The enemy relies on dashes", "Yes"),
  "Qiyana":      ("Assassin", "AD", "wombo, pick, flank", "The enemy has squishy carries and you want a wombo ult", "No"),
  "Rammus":      ("Tank engage", "AP", "teamfight, dive", "The enemy is AD heavy", "Mostly"),
  "Rek'Sai":     ("Early ganker", "AD", "dive, pick", "You want early ganks and objective control", "Mostly"),
  "Rengar":      ("Assassin", "AD", "pick, flank", "The enemy has squishy carries and you can flank", "No"),
  "Sejuani":     ("Tank engage", "AP", "wombo, teamfight, front-to-back", "You need a tank with reliable crowd control", "Yes"),
  "Shaco":       ("Assassin", "AD", "pick, split", "The enemy has squishy carries and poor vision", "No"),
  "Shyvana":     ("Farming carry", "Mixed", "scaling, teamfight", "Your team is safe early and needs a scaling frontline", "Mostly"),
  "Skarner":     ("Tank engage", "AP", "wombo, teamfight, pick", "You need a tank who can pull a carry", "Yes"),
  "Sylas":       ("Skirmisher", "AP", "teamfight, dive, pick", "The enemy has strong ults to steal", "Mostly"),
  "Taliyah":     ("AP carry", "AP", "wombo, teamfight, pick", "You need AP and map control", "Mostly"),
  "Talon":       ("Assassin", "AD", "pick, flank, dive", "You want to roam and the enemy has squishy carries", "Mostly"),
  "Trundle":     ("Skirmisher", "AD", "front-to-back, split", "The enemy has tanks to shred", "Yes"),
  "Udyr":        ("Skirmisher", "Mixed", "teamfight, front-to-back", "You want a tanky, fast-clearing frontline", "Yes"),
  "Vi":          ("Tank engage", "AD", "dive, pick, teamfight", "You need a point-and-click engage on a carry", "Yes"),
  "Viego":       ("Skirmisher", "AD", "teamfight, dive, scaling", "You want a skirmisher who snowballs fights", "Yes"),
  "Volibear":    ("Skirmisher", "Mixed", "dive, teamfight", "You want a tanky diver", "Yes"),
  "Warwick":     ("Skirmisher", "Mixed", "dive, pick", "You want early ganks and sustain", "Yes"),
  "Wukong":      ("Tank engage", "AD", "wombo, teamfight, dive", "You need a wombo engage", "Yes"),
  "Xin Zhao":    ("Early ganker", "AD", "dive, teamfight", "You want early ganks and a reliable duelist", "Yes"),
  "Zac":         ("Tank engage", "AP", "wombo, teamfight", "You need engage from long range", "Yes"),
  "Zyra":        ("AP carry", "AP", "wombo, teamfight, poke", "You need AP and zone control", "Mostly"),
  "Brand":       ("AP carry", "AP", "wombo, teamfight", "The enemy clumps and you need AP", "Mostly"),
  "Gragas":      ("Tank engage", "AP", "wombo, teamfight, pick", "You need AP engage and disengage", "Yes"),
  "Morgana":     ("AP carry", "AP", "wombo, teamfight", "The enemy relies on crowd control", "Mostly"),
  "Cho'Gath":    ("Tank engage", "AP", "teamfight, front-to-back", "You need a tank that scales", "Yes"),
  "Olaf":        ("Skirmisher", "AD", "dive, teamfight", "The enemy relies on crowd control to kite", "Mostly"),
 },
 "bot": {
  "Aphelios":    ("Hypercarry", "AD", "scaling, teamfight, front-to-back", "Your team can protect you and the game goes long", "No"),
  "Ashe":        ("Utility / poke", "AD", "pick, poke, teamfight", "You need engage and the enemy is immobile", "Yes"),
  "Caitlyn":     ("Lane bully", "AD", "poke, siege", "You want lane pressure and siege", "Yes"),
  "Corki":       ("Utility / poke", "Mixed", "poke, siege, scaling", "You need mixed damage and poke", "Mostly"),
  "Draven":      ("Lane bully", "AD", "dive, teamfight", "You want to win lane hard with an engage support", "No"),
  "Ezreal":      ("Mobile skirmisher", "AD", "poke, siege, scaling", "You need a safe pick against dive and poke", "Yes"),
  "Jhin":        ("Utility / poke", "AD", "pick, poke, teamfight", "You want roots and pick potential", "Yes"),
  "Jinx":        ("Hypercarry", "AD", "scaling, teamfight, front-to-back", "Your team can protect you late", "Mostly"),
  "Kai'Sa":      ("Mobile skirmisher", "Mixed", "dive, teamfight, scaling", "Your team has engage to follow", "Mostly"),
  "Kalista":     ("Lane bully", "AD", "dive, teamfight", "You have an engage support to pair with", "No"),
  "Karthus":     ("Mage bot", "AP", "scaling, teamfight", "You need AP damage from bot", "No"),
  "Kog'Maw":     ("Hypercarry", "Mixed", "scaling, front-to-back", "Your team has peel and the enemy has tanks", "No"),
  "Lucian":      ("Lane bully", "AD", "dive, poke, pick", "You want early pressure with an aggressive support", "Mostly"),
  "Miss Fortune":("Lane bully", "AD", "wombo, teamfight, poke", "Your team has crowd control for the ult", "Yes"),
  "Nilah":       ("Mobile skirmisher", "AD", "dive, teamfight, scaling", "You have an enchanter support and melee enemies", "No"),
  "Samira":      ("Mobile skirmisher", "AD", "dive, teamfight, wombo", "You have engage support and the enemy is immobile", "No"),
  "Senna":       ("Utility / poke", "AD", "poke, scaling, front-to-back", "You need range and healing from bot", "Mostly"),
  "Seraphine":   ("Mage bot", "AP", "wombo, teamfight, poke", "You need AP and a teamfight ult", "Mostly"),
  "Sivir":       ("Utility / poke", "AD", "teamfight, siege, scaling", "You need wave clear and a speed engage", "Yes"),
  "Smolder":     ("Hypercarry", "Mixed", "scaling, late, poke", "The game will go long and you can farm safely", "Mostly"),
  "Swain":       ("Mage bot", "AP", "teamfight, front-to-back", "You need AP and a durable bot laner", "Mostly"),
  "Tristana":    ("Lane bully", "AD", "dive, scaling, teamfight", "You want to all-in with an engage support", "Mostly"),
  "Twitch":      ("Hypercarry", "AD", "scaling, flank, teamfight", "The enemy lacks vision control and you have peel", "No"),
  "Varus":       ("Utility / poke", "Mixed", "poke, siege, pick", "You want poke and a lockdown ult", "Yes"),
  "Vayne":       ("Hypercarry", "AD", "scaling, late", "The enemy has tanks and you have peel", "No"),
  "Xayah":       ("Mobile skirmisher", "AD", "teamfight, scaling", "The enemy has divers you need to shrug off", "Yes"),
  "Yunara":      ("Hypercarry", "AD", "scaling, teamfight", "You want a scaling marksman", "Mostly"),
  "Zeri":        ("Mobile skirmisher", "AD", "scaling, teamfight, dive", "You have an enchanter and the game goes long", "No"),
  "Ziggs":       ("Mage bot", "AP", "siege, poke, scaling", "You need AP and tower pressure", "Mostly"),
  "Brand":       ("Mage bot", "AP", "wombo, teamfight, poke", "You need AP burst from bot", "Mostly"),
  "Hwei":        ("Mage bot", "AP", "poke, teamfight, scaling", "You need AP and wave control", "Mostly"),
  "Veigar":      ("Mage bot", "AP", "scaling, pick, teamfight", "You need AP and the game goes long", "Mostly"),
  "Jayce":       ("Utility / poke", "AD", "poke, siege", "You want poke from bot", "Mostly"),
  "Akshan":      ("Mobile skirmisher", "AD", "pick, dive", "You want a mobile marksman", "No"),
 },
 "support": {
  "Alistar":     ("Engage", "AP", "dive, teamfight, wombo", "You need hard engage and your carry needs peel", "Yes"),
  "Bard":        ("Poke mage", "AP", "pick, poke, teamfight", "You want roams and pick potential", "Mostly"),
  "Blitzcrank":  ("Hook", "AP", "pick", "The enemy has squishy, immobile champions", "No"),
  "Brand":       ("Poke mage", "AP", "wombo, teamfight, poke", "You need AP damage from support", "Mostly"),
  "Braum":       ("Peel tank", "AP", "front-to-back, teamfight", "The enemy has dive or projectile-heavy damage", "Yes"),
  "Janna":       ("Enchanter", "AP", "front-to-back, teamfight", "The enemy has dive and your carry scales", "Yes"),
  "Karma":       ("Enchanter", "AP", "poke, siege, teamfight", "You want poke in lane and shields later", "Yes"),
  "Leona":       ("Engage", "AP", "dive, teamfight, wombo", "You want to all-in in lane and engage fights", "Mostly"),
  "Lulu":        ("Enchanter", "AP", "front-to-back, scaling", "You have a hypercarry to protect", "Yes"),
  "Lux":         ("Poke mage", "AP", "poke, pick, siege", "You want poke and the enemy is immobile", "Mostly"),
  "Maokai":      ("Engage", "AP", "wombo, teamfight, front-to-back", "You need a tank support with engage", "Yes"),
  "Milio":       ("Enchanter", "AP", "front-to-back, scaling", "The enemy has crowd control to cleanse", "Yes"),
  "Morgana":     ("Poke mage", "AP", "pick, teamfight", "The enemy has hooks or key crowd control", "Yes"),
  "Nami":        ("Enchanter", "AP", "teamfight, poke, front-to-back", "You want lane trades and a teamfight wave", "Yes"),
  "Nautilus":    ("Hook", "AP", "pick, dive, teamfight, wombo", "You want a reliable engage and pick", "Yes"),
  "Neeko":       ("Poke mage", "AP", "wombo, teamfight, pick", "You need AP and a wombo root", "Mostly"),
  "Pantheon":    ("Engage", "AD", "dive, pick", "You want early all-ins and a global", "Mostly"),
  "Poppy":       ("Peel tank", "AD", "teamfight, pick", "The enemy relies on dashes", "Yes"),
  "Pyke":        ("Hook", "AD", "pick, dive", "The enemy is squishy and you want to roam", "No"),
  "Rakan":       ("Engage", "AP", "wombo, teamfight, dive", "You need a mobile engage and peel", "Yes"),
  "Rell":        ("Engage", "AP", "wombo, teamfight, dive", "You need a hard engage against squishies", "Mostly"),
  "Renata Glasc":("Enchanter", "AP", "teamfight, front-to-back, wombo", "The enemy clumps and your carry needs saving", "Yes"),
  "Senna":       ("Poke mage", "AD", "poke, scaling, front-to-back", "You want range and healing", "Mostly"),
  "Seraphine":   ("Enchanter", "AP", "wombo, teamfight, poke", "You want poke and a teamfight ult", "Yes"),
  "Sona":        ("Enchanter", "AP", "scaling, teamfight, front-to-back", "Your lane can survive early and scale", "Mostly"),
  "Soraka":      ("Enchanter", "AP", "front-to-back, scaling", "Your carry needs healing and the enemy lacks dive", "Mostly"),
  "Swain":       ("Poke mage", "AP", "teamfight, pick", "You want a durable AP support with pull", "Mostly"),
  "Tahm Kench":  ("Peel tank", "AP", "front-to-back, teamfight", "The enemy has dive or assassins", "Yes"),
  "Taric":       ("Peel tank", "AP", "teamfight, dive, front-to-back", "You want invulnerability for dives", "Mostly"),
  "Thresh":      ("Hook", "AP", "pick, teamfight, front-to-back", "You want a flexible hook and peel", "Yes"),
  "Vel'Koz":     ("Poke mage", "AP", "poke, siege", "You want poke and the enemy has tanks", "Mostly"),
  "Xerath":      ("Poke mage", "AP", "poke, siege", "You want long-range poke and siege", "Mostly"),
  "Yuumi":       ("Enchanter", "AP", "front-to-back, scaling", "You have a hypercarry or a duelist to ride", "Mostly"),
  "Zilean":      ("Enchanter", "AP", "pick, teamfight, scaling", "You want speed and a revive for a carry", "Yes"),
  "Zyra":        ("Poke mage", "AP", "wombo, teamfight, poke", "You need AP damage and zone control", "Mostly"),
  "Shen":        ("Peel tank", "Mixed", "teamfight, front-to-back", "You want a global and peel", "Yes"),
  "Elise":       ("Engage", "AP", "pick, dive", "You want aggressive early plays", "No"),
 },
}

# Mid archetypes as used in midlane_overview.xlsx (hand-made). Words match picker.ARCH_WORDS.
ARCHETYPES["mid"] = {
    "Control mage":     (["mages", "immobile"], "melee that must walk through zone control", "assassins and long-range poke"),
    "Artillery":        (["mages", "immobile", "long range", "poke"], "immobile champions and short-range mages", "assassins and dive"),
    "Utility mage":     (["mages"], "comps that need safe wave control", "all-in assassins"),
    "AD assassin":      (["assassins", "ad assassin", "dive"], "immobile squishy mages", "tanky or self-peeling champions"),
    "AP assassin":      (["assassins", "ap assassin", "dive", "ap"], "immobile squishy mages", "champions with point-and-click CC or shields"),
    "Melee carry":      (["melee", "dash"], "short-range mages it can gap-close on", "ranged poke and kiting"),
    "Melee skirmisher": (["melee"], "squishy champions in extended trades", "ranged poke and hard CC"),
    "Scaling":          (["mages", "scaling"], "passive lanes it can farm through", "early lane bullies and roamers"),
    "Roamer":           (["immobile"], "immobile mids it can shove and leave", "champions that punish absence with push"),
}

# Mid archetypes for non-mage mids (added 2026-10-09)
ARCHETYPES["mid"]["Tank / bruiser"] = (["tank", "tanks", "melee", "bruiser"], "assassins that cannot kill it and short-range mages", "ranged poke and % health damage")
ARCHETYPES["mid"]["Marksman"] = (["marksman", "ranged ad", "adc"], "immobile mages it can shove in and dive with the jungler", "assassins and all-in melee")

# Hand entries for champions that were 'Flex' after the 2026-10-09 rebuild. Locke (all roles) and Zaahen (top) are
# too new to classify here; fill them in when their kits are clear.
CHAMPS.setdefault("mid", {}).update({
  "Akshan":      ("Marksman", "AD", "pick, dive, split", "You want a mobile AD mid and revive utility", "No"),
  "Anivia":      ("Control mage", "AP", "teamfight, front-to-back, scaling", "You want zone control and wave clear into melee", "Mostly"),
  "Aurora":      ("Utility mage", "AP", "teamfight, pick, poke", "You want a mobile mage that bullies melee", "Mostly"),
  "Cho'Gath":    ("Tank / bruiser", "AP", "teamfight, front-to-back, scaling", "You need a frontline and the lane is passive", "Yes"),
  "Irelia":      ("Melee carry", "AD", "dive, split, teamfight", "You want a melee carry that punishes immobile mages", "No"),
  "Kog'Maw":     ("Artillery", "AP", "poke, siege, scaling", "You want long-range AP poke", "No"),
  "Malphite":    ("Tank / bruiser", "AP", "wombo, teamfight, dive", "The enemy is AD heavy and you want a wombo ult", "Yes"),
  "Mel":         ("Control mage", "AP", "teamfight, poke, scaling", "You want long-range AP and projectile denial", "Mostly"),
  "Nasus":       ("Tank / bruiser", "AD", "split, scaling", "You want a split pusher and the lane is passive", "Mostly"),
  "Sion":        ("Tank / bruiser", "AD", "teamfight, front-to-back, split", "You want a tank with wave clear and a long engage", "Yes"),
  "Swain":       ("Control mage", "AP", "teamfight, front-to-back", "You want a drain-tank mage into melee", "Mostly"),
  "Tristana":    ("Marksman", "AD", "dive, siege, scaling", "You need AD damage and tower pressure", "Mostly"),
  "Veigar":      ("Scaling", "AP", "teamfight, scaling, pick", "You want infinite scaling and the lane is passive", "Mostly"),
  "Zoe":         ("Artillery", "AP", "poke, pick", "You want long-range pick and burst", "No"),
})
CHAMPS["jungle"].update({
  "Aatrox":      ("Skirmisher", "AD", "teamfight, dive", "You want a drain-tank fighter jungle", "Mostly"),
  "Ambessa":     ("Skirmisher", "AD", "dive, skirmish", "You want an early skirmisher with mobility", "No"),
  "Fizz":        ("Assassin", "AP", "pick, dive", "You need AP burst and the enemy is squishy", "No"),
  "Gwen":        ("Skirmisher", "AP", "split, teamfight, scaling", "You want an AP fighter that shreds tanks", "Mostly"),
  "Jayce":       ("Skirmisher", "AD", "poke, siege", "You want an early-game poke jungler", "No"),
  "Malphite":    ("Tank engage", "AP", "wombo, teamfight", "The enemy is AD heavy and you want engage", "Yes"),
  "Quinn":       ("Early ganker", "AD", "pick, split", "You want map pressure and early ganks", "No"),
  "Zed":         ("Assassin", "AD", "pick, dive, split", "You need AD burst into squishies", "No"),
})
CHAMPS["bot"].update({
  "Aurelion Sol": ("Mage bot", "AP", "teamfight, scaling", "You want AP scaling in the bot lane", "Mostly"),
  "Katarina":    ("Mobile skirmisher", "AP", "dive, teamfight", "You want an AP reset carry bot", "No"),
  "Lux":         ("Mage bot", "AP", "poke, pick, siege", "You want AP poke and pick bot", "Mostly"),
  "Mel":         ("Mage bot", "AP", "poke, teamfight", "You want long-range AP bot", "Mostly"),
  "Syndra":      ("Mage bot", "AP", "poke, pick, teamfight", "You want AP burst bot", "Mostly"),
  "Vel'Koz":     ("Mage bot", "AP", "poke, siege", "You want true-damage poke bot", "Mostly"),
  "Viktor":      ("Mage bot", "AP", "teamfight, siege, scaling", "You want AP wave clear and scaling bot", "Mostly"),
  "Vladimir":    ("Mage bot", "AP", "teamfight, scaling", "You want a drain-tank AP bot", "Mostly"),
  "Xerath":      ("Mage bot", "AP", "poke, siege", "You want long-range AP poke bot", "Mostly"),
  "Yasuo":       ("Mobile skirmisher", "AD", "wombo, teamfight, dive", "Your team has knock-ups and you want a melee bot", "No"),
})
CHAMPS["support"].update({
  "Amumu":       ("Engage", "AP", "wombo, teamfight", "You want AoE engage and the enemy clumps", "Yes"),
  "Anivia":      ("Poke mage", "AP", "teamfight, pick", "You want wall plays and zone control", "Mostly"),
  "Ashe":        ("Poke mage", "AD", "poke, pick", "You want a global engage tool and slows", "Mostly"),
  "Camille":     ("Engage", "AD", "pick, dive", "You want a dive support that isolates a carry", "No"),
  "Galio":       ("Peel tank", "AP", "teamfight, front-to-back", "The enemy is AP heavy and you want a global", "Yes"),
  "Hwei":        ("Poke mage", "AP", "poke, teamfight, pick", "You want AP poke and utility", "Mostly"),
  "LeBlanc":     ("Poke mage", "AP", "pick, poke", "You want roaming chain-CC picks", "No"),
  "Mel":         ("Poke mage", "AP", "poke, teamfight", "You want long-range poke support", "Mostly"),
  "Shaco":       ("Engage", "AP", "pick, split", "You want vision denial and surprise picks", "No"),
  "Sylas":       ("Engage", "AP", "pick, dive, teamfight", "The enemy has strong ults to steal", "No"),
  "Teemo":       ("Poke mage", "AP", "poke, siege", "You want blind and vision control against AD", "No"),
  "Veigar":      ("Poke mage", "AP", "pick, teamfight, scaling", "You want cage plays and scaling AP", "Mostly"),
  "Zoe":         ("Poke mage", "AP", "poke, pick", "You want long-range pick and burst", "No"),
})
